<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
    
<!-- centre point of the box is at (width/2 , length/2, height/2) -->
 <xacro:macro name="support_box" params="name vis_size_xyz coll_size_xyz box_col">
   <link name="${name}">
    	<visual>
    		<origin xyz= "0 0 0" rpy ="0 0 0"/>
    		<geometry>
    			<box size="${vis_size_xyz}"/>
    		</geometry>
    		<material name="${box_col}"/>
    	</visual>
    	<collision>
    		<origin xyz= "0 0 0" rpy ="0 0 0"/>
    		<geometry>
    			<box size="${coll_size_xyz}"/>
    		</geometry>
    	</collision>
    </link>
 </xacro:macro>

 <!-- centre point of the cylinder is at (0, 0, length/2) -->
 <xacro:macro name="support_cylinder" params="name radius length color">
   <link name="${name}">
        <visual>
            <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${radius}" length="${length}"/>
            </geometry>
            <material name="${color}"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${radius}" length="${length}"/>
            </geometry>
        </collision>
    </link>
 </xacro:macro> 

</robot>
